name: wavecurrent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib=3.1.3
  - numpy=1.18.1
  - netcdf4=1.5.3
  - libnetcdf=4.7.3
  - cmocean=2.0
  - scipy=1.4.1
  - pandas=1.0.0
  - xarray=0.15.0
  - dask=2.10.1
  - xrft=0.2.0
  - seawater=3.3.4
  - seaborn=0.10.0
